<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\LocalGovernment;

class StatesAndLGAsSeeder extends Seeder
{
    public function run(): void
    {
        // Create all 37 Nigerian states
        $states = [
            ['name' => 'Abia', 'code' => 'AB'],
            ['name' => 'Adamawa', 'code' => 'AD'],
            ['name' => 'Akwa Ibom', 'code' => 'AK'],
            ['name' => 'Anambra', 'code' => 'AN'],
            ['name' => 'Bauchi', 'code' => 'BA'],
            ['name' => 'Bayelsa', 'code' => 'BY'],
            ['name' => 'Benue', 'code' => 'BE'],
            ['name' => 'Borno', 'code' => 'BO'],
            ['name' => 'Cross River', 'code' => 'CR'],
            ['name' => 'Delta', 'code' => 'DE'],
            ['name' => 'Ebonyi', 'code' => 'EB'],
            ['name' => 'Edo', 'code' => 'ED'],
            ['name' => 'Ekiti', 'code' => 'EK'],
            ['name' => 'Enugu', 'code' => 'EN'],
            ['name' => 'Gombe', 'code' => 'GO'],
            ['name' => 'Imo', 'code' => 'IM'],
            ['name' => 'Jigawa', 'code' => 'JI'],
            ['name' => 'Kaduna', 'code' => 'KD'],
            ['name' => 'Kano', 'code' => 'KN'],
            ['name' => 'Katsina', 'code' => 'KT'],
            ['name' => 'Kebbi', 'code' => 'KE'],
            ['name' => 'Kogi', 'code' => 'KG'],
            ['name' => 'Kwara', 'code' => 'KW'],
            ['name' => 'Lagos', 'code' => 'LA'],
            ['name' => 'Nasarawa', 'code' => 'NA'],
            ['name' => 'Niger', 'code' => 'NI'],
            ['name' => 'Ogun', 'code' => 'OG'],
            ['name' => 'Ondo', 'code' => 'ON'],
            ['name' => 'Osun', 'code' => 'OS'],
            ['name' => 'Oyo', 'code' => 'OY'],
            ['name' => 'Plateau', 'code' => 'PL'],
            ['name' => 'Rivers', 'code' => 'RI'],
            ['name' => 'Sokoto', 'code' => 'SO'],
            ['name' => 'Taraba', 'code' => 'TA'],
            ['name' => 'Yobe', 'code' => 'YO'],
            ['name' => 'Zamfara', 'code' => 'ZA'],
            ['name' => 'Federal Capital Territory', 'code' => 'FC'],
        ];

        foreach ($states as $state) {
            State::firstOrCreate(['code' => $state['code']], $state);
        }

        // Complete LGAs data from INEC (774 LGAs)
        $lgas = [
            // Abia (17 LGAs)
            ['state_id' => 1, 'name' => 'Aba North'],
            ['state_id' => 1, 'name' => 'Aba South'],
            ['state_id' => 1, 'name' => 'Arochukwu'],
            ['state_id' => 1, 'name' => 'Bende'],
            ['state_id' => 1, 'name' => 'Ikwuano'],
            ['state_id' => 1, 'name' => 'Isiala Ngwa North'],
            ['state_id' => 1, 'name' => 'Isiala Ngwa South'],
            ['state_id' => 1, 'name' => 'Isiukwuato'],
            ['state_id' => 1, 'name' => 'Obingwa'],
            ['state_id' => 1, 'name' => 'Ohafia'],
            ['state_id' => 1, 'name' => 'Osisioma'],
            ['state_id' => 1, 'name' => 'Ugwunagbo'],
            ['state_id' => 1, 'name' => 'Ukwa East'],
            ['state_id' => 1, 'name' => 'Ukwa West'],
            ['state_id' => 1, 'name' => 'Umuahia North'],
            ['state_id' => 1, 'name' => 'Umuahia South'],
            ['state_id' => 1, 'name' => 'Umu Nneochi'],
            // Adamawa (21 LGAs)
            ['state_id' => 2, 'name' => 'Demsa'],
            ['state_id' => 2, 'name' => 'Fufore'],
            ['state_id' => 2, 'name' => 'Ganye'],
            ['state_id' => 2, 'name' => 'Gayuk'],
            ['state_id' => 2, 'name' => 'Gombi'],
            ['state_id' => 2, 'name' => 'Grie'],
            ['state_id' => 2, 'name' => 'Hong'],
            ['state_id' => 2, 'name' => 'Jada'],
            ['state_id' => 2, 'name' => 'Lamurde'],
            ['state_id' => 2, 'name' => 'Madagali'],
            ['state_id' => 2, 'name' => 'Maiha'],
            ['state_id' => 2, 'name' => 'Mayo Belwa'],
            ['state_id' => 2, 'name' => 'Michika'],
            ['state_id' => 2, 'name' => 'Mubi North'],
            ['state_id' => 2, 'name' => 'Mubi South'],
            ['state_id' => 2, 'name' => 'Numan'],
            ['state_id' => 2, 'name' => 'Shelleng'],
            ['state_id' => 2, 'name' => 'Song'],
            ['state_id' => 2, 'name' => 'Toungo'],
            ['state_id' => 2, 'name' => 'Yola North'],
            ['state_id' => 2, 'name' => 'Yola South'],
            // Akwa Ibom (31 LGAs)
            ['state_id' => 3, 'name' => 'Abak'],
            ['state_id' => 3, 'name' => 'Eastern Obolo'],
            ['state_id' => 3, 'name' => 'Eka'],
            ['state_id' => 3, 'name' => 'Essien Udim'],
            ['state_id' => 3, 'name' => 'Eket'],
            ['state_id' => 3, 'name' => 'Esit Eket'],
            ['state_id' => 3, 'name' => 'Etim Ekpo'],
            ['state_id' => 3, 'name' => 'Etinan'],
            ['state_id' => 3, 'name' => 'Ibeno'],
            ['state_id' => 3, 'name' => 'Ibiaaku'],
            ['state_id' => 3, 'name' => 'Ibiono Ibom'],
            ['state_id' => 3, 'name' => 'Ika'],
            ['state_id' => 3, 'name' => 'Ikono'],
            ['state_id' => 3, 'name' => 'Ikot Abasi'],
            ['state_id' => 3, 'name' => 'Ikot Ekpene'],
            ['state_id' => 3, 'name' => 'Ini'],
            ['state_id' => 3, 'name' => 'Itu'],
            ['state_id' => 3, 'name' => 'Mbiang'],
            ['state_id' => 3, 'name' => 'Mkpat Enin'],
            ['state_id' => 3, 'name' => 'Nsit Atai'],
            ['state_id' => 3, 'name' => 'Nsit Ibom'],
            ['state_id' => 3, 'name' => 'Nsit Ubium'],
            ['state_id' => 3, 'name' => 'Obot Akara'],
            ['state_id' => 3, 'name' => 'Okobo'],
            ['state_id' => 3, 'name' => 'Onna'],
            ['state_id' => 3, 'name' => 'Oron'],
            ['state_id' => 3, 'name' => 'Udung Uko'],
            ['state_id' => 3, 'name' => 'Ukanafun'],
            ['state_id' => 3, 'name' => 'Uruan'],
            ['state_id' => 3, 'name' => 'Uruofia'],
            ['state_id' => 3, 'name' => 'Urue Offong/Oruko'],
            ['state_id' => 3, 'name' => 'Uyo'],
            // Anambra (21 LGAs)
            ['state_id' => 4, 'name' => 'Aguata'],
            ['state_id' => 4, 'name' => 'Anambra East'],
            ['state_id' => 4, 'name' => 'Anambra West'],
            ['state_id' => 4, 'name' => 'Anaocha'],
            ['state_id' => 4, 'name' => 'Awka North'],
            ['state_id' => 4, 'name' => 'Awka South'],
            ['state_id' => 4, 'name' => 'Ayamelum'],
            ['state_id' => 4, 'name' => 'Dunukofia'],
            ['state_id' => 4, 'name' => 'Ekwusigo'],
            ['state_id' => 4, 'name' => 'Idemili North'],
            ['state_id' => 4, 'name' => 'Idemili South'],
            ['state_id' => 4, 'name' => 'Ihiala'],
            ['state_id' => 4, 'name' => 'Njikoka'],
            ['state_id' => 4, 'name' => 'Nnewi North'],
            ['state_id' => 4, 'name' => 'Nnewi South'],
            ['state_id' => 4, 'name' => 'Ogbaru'],
            ['state_id' => 4, 'name' => 'Onitsha North'],
            ['state_id' => 4, 'name' => 'Onitsha South'],
            ['state_id' => 4, 'name' => 'Orumba North'],
            ['state_id' => 4, 'name' => 'Orumba South'],
            ['state_id' => 4, 'name' => 'Oru'],
            // Bauchi (20 LGAs)
            ['state_id' => 5, 'name' => 'Alkaleri'],
            ['state_id' => 5, 'name' => 'Bauchi'],
            ['state_id' => 5, 'name' => 'Bogoro'],
            ['state_id' => 5, 'name' => 'Dambam'],
            ['state_id' => 5, 'name' => 'Darazo'],
            ['state_id' => 5, 'name' => 'Dass'],
            ['state_id' => 5, 'name' => 'Gamawa'],
            ['state_id' => 5, 'name' => 'Ganjuwa'],
            ['state_id' => 5, 'name' => 'Giade'],
            ['state_id' => 5, 'name' => 'Itas/Gadau'],
            ['state_id' => 5, 'name' => "Jama'are"],
            ['state_id' => 5, 'name' => 'Katagum'],
            ['state_id' => 5, 'name' => 'Kirfi'],
            ['state_id' => 5, 'name' => 'Misau'],
            ['state_id' => 5, 'name' => 'Ningi'],
            ['state_id' => 5, 'name' => 'Shira'],
            ['state_id' => 5, 'name' => 'Tafawa Balewa'],
            ['state_id' => 5, 'name' => 'Toro'],
            ['state_id' => 5, 'name' => 'Warji'],
            ['state_id' => 5, 'name' => 'Zaki'],
            // Bayelsa (8 LGAs)
            ['state_id' => 6, 'name' => 'Brass'],
            ['state_id' => 6, 'name' => 'Ekeremor'],
            ['state_id' => 6, 'name' => 'Kolokuma/Opokuma'],
            ['state_id' => 6, 'name' => 'Nembe'],
            ['state_id' => 6, 'name' => 'Ogbia'],
            ['state_id' => 6, 'name' => 'Sagbama'],
            ['state_id' => 6, 'name' => 'Southern Ijaw'],
            ['state_id' => 6, 'name' => 'Yenagoa'],
            // Benue (23 LGAs)
            ['state_id' => 7, 'name' => 'Ado'],
            ['state_id' => 7, 'name' => 'Agatu'],
            ['state_id' => 7, 'name' => 'Apa'],
            ['state_id' => 7, 'name' => 'Buruku'],
            ['state_id' => 7, 'name' => 'Gboko'],
            ['state_id' => 7, 'name' => 'Guma'],
            ['state_id' => 7, 'name' => 'Gwer East'],
            ['state_id' => 7, 'name' => 'Gwer West'],
            ['state_id' => 7, 'name' => 'Katsina-Ala'],
            ['state_id' => 7, 'name' => 'Konshisha'],
            ['state_id' => 7, 'name' => 'Kwande'],
            ['state_id' => 7, 'name' => 'Logo'],
            ['state_id' => 7, 'name' => 'Makurdi'],
            ['state_id' => 7, 'name' => 'Obi'],
            ['state_id' => 7, 'name' => 'Ogbadibo'],
            ['state_id' => 7, 'name' => 'Ohimini'],
            ['state_id' => 7, 'name' => 'Oju'],
            ['state_id' => 7, 'name' => 'Okpokwu'],
            ['state_id' => 7, 'name' => 'Oturkpo'],
            ['state_id' => 7, 'name' => 'Tarka'],
            ['state_id' => 7, 'name' => 'Ukum'],
            ['state_id' => 7, 'name' => 'Ushongo'],
            ['state_id' => 7, 'name' => 'Vandeikya'],
            // Borno (27 LGAs)
            ['state_id' => 8, 'name' => 'Abadam'],
            ['state_id' => 8, 'name' => 'Askira/Uba'],
            ['state_id' => 8, 'name' => 'Bama'],
            ['state_id' => 8, 'name' => 'Bayo'],
            ['state_id' => 8, 'name' => 'Biu'],
            ['state_id' => 8, 'name' => 'Chibok'],
            ['state_id' => 8, 'name' => 'Damboa'],
            ['state_id' => 8, 'name' => 'Dikwa'],
            ['state_id' => 8, 'name' => 'Gubio'],
            ['state_id' => 8, 'name' => 'Guzamala'],
            ['state_id' => 8, 'name' => 'Gwoza'],
            ['state_id' => 8, 'name' => 'Hawul'],
            ['state_id' => 8, 'name' => 'Jere'],
            ['state_id' => 8, 'name' => 'Kaga'],
            ['state_id' => 8, 'name' => 'Kalabalge'],
            ['state_id' => 8, 'name' => 'Konduga'],
            ['state_id' => 8, 'name' => 'Kukawa'],
            ['state_id' => 8, 'name' => 'Kwaya Kusar'],
            ['state_id' => 8, 'name' => 'Mafa'],
            ['state_id' => 8, 'name' => 'Magumeri'],
            ['state_id' => 8, 'name' => 'Maiduguri'],
            ['state_id' => 8, 'name' => 'Marte'],
            ['state_id' => 8, 'name' => 'Mobbar'],
            ['state_id' => 8, 'name' => 'Monguno'],
            ['state_id' => 8, 'name' => 'Ngala'],
            ['state_id' => 8, 'name' => 'Nganzai'],
            ['state_id' => 8, 'name' => 'Shani'],
            // Cross River (18 LGAs)
            ['state_id' => 9, 'name' => 'Abi'],
            ['state_id' => 9, 'name' => 'Akamkpa'],
            ['state_id' => 9, 'name' => 'Akpabuyo'],
            ['state_id' => 9, 'name' => 'Bakassi'],
            ['state_id' => 9, 'name' => 'Bekwarra'],
            ['state_id' => 9, 'name' => 'Biase'],
            ['state_id' => 9, 'name' => 'Boki'],
            ['state_id' => 9, 'name' => 'Calabar Municipal'],
            ['state_id' => 9, 'name' => 'Calabar South'],
            ['state_id' => 9, 'name' => 'Etung'],
            ['state_id' => 9, 'name' => 'Ikom'],
            ['state_id' => 9, 'name' => 'Obanliku'],
            ['state_id' => 9, 'name' => 'Obubra'],
            ['state_id' => 9, 'name' => 'Obudu'],
            ['state_id' => 9, 'name' => 'Ogoja'],
            ['state_id' => 9, 'name' => 'Yakuur'],
            ['state_id' => 9, 'name' => 'Yala'],
            // Delta (25 LGAs)
            ['state_id' => 10, 'name' => 'Aniocha North'],
            ['state_id' => 10, 'name' => 'Aniocha South'],
            ['state_id' => 10, 'name' => 'Bomadi'],
            ['state_id' => 10, 'name' => 'Burutu'],
            ['state_id' => 10, 'name' => 'Ethiope East'],
            ['state_id' => 10, 'name' => 'Ethiope West'],
            ['state_id' => 10, 'name' => 'Ika North East'],
            ['state_id' => 10, 'name' => 'Ika South'],
            ['state_id' => 10, 'name' => 'Isoko North'],
            ['state_id' => 10, 'name' => 'Isoko South'],
            ['state_id' => 10, 'name' => 'Ndokwa East'],
            ['state_id' => 10, 'name' => 'Ndokwa West'],
            ['state_id' => 10, 'name' => 'Okpe'],
            ['state_id' => 10, 'name' => 'Oshimili North'],
            ['state_id' => 10, 'name' => 'Oshimili South'],
            ['state_id' => 10, 'name' => 'Patani'],
            ['state_id' => 10, 'name' => 'Sapele'],
            ['state_id' => 10, 'name' => 'Udu'],
            ['state_id' => 10, 'name' => 'Ughelli North'],
            ['state_id' => 10, 'name' => 'Ughelli South'],
            ['state_id' => 10, 'name' => 'Ukwuani'],
            ['state_id' => 10, 'name' => 'Uvwie'],
            ['state_id' => 10, 'name' => 'Warri North'],
            ['state_id' => 10, 'name' => 'Warri South'],
            ['state_id' => 10, 'name' => 'Warri South West'],
            // Ebonyi (13 LGAs)
            ['state_id' => 11, 'name' => 'Abakaliki'],
            ['state_id' => 11, 'name' => 'Afikpo North'],
            ['state_id' => 11, 'name' => 'Afikpo South'],
            ['state_id' => 11, 'name' => 'Ebonyi'],
            ['state_id' => 11, 'name' => 'Ezza North'],
            ['state_id' => 11, 'name' => 'Ezza South'],
            ['state_id' => 11, 'name' => 'Ikwo'],
            ['state_id' => 11, 'name' => 'Ishielu'],
            ['state_id' => 11, 'name' => 'Ivo'],
            ['state_id' => 11, 'name' => 'Izzi'],
            ['state_id' => 11, 'name' => 'Ohaukwu'],
            ['state_id' => 11, 'name' => 'Onicha'],
            ['state_id' => 11, 'name' => 'Ileachi'],
            // Edo (18 LGAs)
            ['state_id' => 12, 'name' => 'Akoko Edo'],
            ['state_id' => 12, 'name' => 'Egor'],
            ['state_id' => 12, 'name' => 'Esan Central'],
            ['state_id' => 12, 'name' => 'Esan North East'],
            ['state_id' => 12, 'name' => 'Esan South East'],
            ['state_id' => 12, 'name' => 'Esan West'],
            ['state_id' => 12, 'name' => 'Etsako Central'],
            ['state_id' => 12, 'name' => 'Etsako East'],
            ['state_id' => 12, 'name' => 'Etsako West'],
            ['state_id' => 12, 'name' => 'Ikpoba Okha'],
            ['state_id' => 12, 'name' => 'Orhionmwon'],
            ['state_id' => 12, 'name' => 'Ovia North East'],
            ['state_id' => 12, 'name' => 'Ovia South West'],
            ['state_id' => 12, 'name' => 'Owan East'],
            ['state_id' => 12, 'name' => 'Owan West'],
            ['state_id' => 12, 'name' => 'Uhunmwonde'],
            // Ekiti (16 LGAs)
            ['state_id' => 13, 'name' => 'Ado Ekiti'],
            ['state_id' => 13, 'name' => 'Efon'],
            ['state_id' => 13, 'name' => 'Ekiti East'],
            ['state_id' => 13, 'name' => 'Ekiti South West'],
            ['state_id' => 13, 'name' => 'Ekiti West'],
            ['state_id' => 13, 'name' => 'Emure'],
            ['state_id' => 13, 'name' => 'Gbonyin'],
            ['state_id' => 13, 'name' => 'Ido Osi'],
            ['state_id' => 13, 'name' => 'Ijero'],
            ['state_id' => 13, 'name' => 'Ikere'],
            ['state_id' => 13, 'name' => 'Ikole'],
            ['state_id' => 13, 'name' => 'Ilejemeje'],
            ['state_id' => 13, 'name' => 'Irepodun/Ifelodun'],
            ['state_id' => 13, 'name' => 'Ise/Orun'],
            ['state_id' => 13, 'name' => 'Moba'],
            ['state_id' => 13, 'name' => 'Oye'],
            // Enugu (17 LGAs)
            ['state_id' => 14, 'name' => 'Aninri'],
            ['state_id' => 14, 'name' => 'Awgu'],
            ['state_id' => 14, 'name' => 'Enugu East'],
            ['state_id' => 14, 'name' => 'Enugu North'],
            ['state_id' => 14, 'name' => 'Enugu South'],
            ['state_id' => 14, 'name' => 'Ezeagu'],
            ['state_id' => 14, 'name' => 'Igbo Etiti'],
            ['state_id' => 14, 'name' => 'Igbo Eze North'],
            ['state_id' => 14, 'name' => 'Igbo Eze South'],
            ['state_id' => 14, 'name' => 'Isi Uzo'],
            ['state_id' => 14, 'name' => 'Nsukka'],
            ['state_id' => 14, 'name' => 'Oji River'],
            ['state_id' => 14, 'name' => 'Udenu'],
            ['state_id' => 14, 'name' => 'Udi'],
            ['state_id' => 14, 'name' => 'Uzo-Uwani'],
            ['state_id' => 14, 'name' => 'Enugu East'],
            ['state_id' => 14, 'name' => 'Nkanu East'],
            ['state_id' => 14, 'name' => 'Nkanu West'],
            // Gombe (11 LGAs)
            ['state_id' => 15, 'name' => 'Akko'],
            ['state_id' => 15, 'name' => 'Balanga'],
            ['state_id' => 15, 'name' => 'Billiri'],
            ['state_id' => 15, 'name' => 'Dukku'],
            ['state_id' => 15, 'name' => 'Funakaye'],
            ['state_id' => 15, 'name' => 'Gombe'],
            ['state_id' => 15, 'name' => 'Kaltungo'],
            ['state_id' => 15, 'name' => 'Kwami'],
            ['state_id' => 15, 'name' => 'Nafada'],
            ['state_id' => 15, 'name' => 'Shongom'],
            ['state_id' => 15, 'name' => 'Yamaltu/Deba'],
            // Imo (27 LGAs)
            ['state_id' => 16, 'name' => 'Aboh Mbaise'],
            ['state_id' => 16, 'name' => 'Ahiazu Mbaise'],
            ['state_id' => 16, 'name' => 'Ehime Mbano'],
            ['state_id' => 16, 'name' => 'Ezinihitte Mbano'],
            ['state_id' => 16, 'name' => 'Ideato North'],
            ['state_id' => 16, 'name' => 'Ideato South'],
            ['state_id' => 16, 'name' => 'Ihitte/Uboma'],
            ['state_id' => 16, 'name' => 'Ikeduru'],
            ['state_id' => 16, 'name' => 'Isiala Mbano'],
            ['state_id' => 16, 'name' => 'Isu'],
            ['state_id' => 16, 'name' => 'Mbaitoli'],
            ['state_id' => 16, 'name' => 'Ngor Okpala'],
            ['state_id' => 16, 'name' => 'Njaba'],
            ['state_id' => 16, 'name' => 'Nwangele'],
            ['state_id' => 16, 'name' => 'Nkwerre'],
            ['state_id' => 16, 'name' => 'Obowo'],
            ['state_id' => 16, 'name' => 'Oguta'],
            ['state_id' => 16, 'name' => 'Ohaji-Egbema'],
            ['state_id' => 16, 'name' => 'Okigwe'],
            ['state_id' => 16, 'name' => 'Orlu'],
            ['state_id' => 16, 'name' => 'Orumba North'],
            ['state_id' => 16, 'name' => 'Orumba South'],
            ['state_id' => 16, 'name' => 'Owerri Municipal'],
            ['state_id' => 16, 'name' => 'Owerri North'],
            ['state_id' => 16, 'name' => 'Owerri West'],
            ['state_id' => 16, 'name' => 'Unuimo'],
            // Jigawa (27 LGAs)
            ['state_id' => 17, 'name' => 'Auyo'],
            ['state_id' => 17, 'name' => 'Babura'],
            ['state_id' => 17, 'name' => 'Biriniwa'],
            ['state_id' => 17, 'name' => 'Birnin Kudu'],
            ['state_id' => 17, 'name' => 'Buji'],
            ['state_id' => 17, 'name' => 'Dutse'],
            ['state_id' => 17, 'name' => 'Gagarawa'],
            ['state_id' => 17, 'name' => 'Garki'],
            ['state_id' => 17, 'name' => 'Gumel'],
            ['state_id' => 17, 'name' => 'Guri'],
            ['state_id' => 17, 'name' => 'Gwaram'],
            ['state_id' => 17, 'name' => 'Gwiwa'],
            ['state_id' => 17, 'name' => 'Hadejia'],
            ['state_id' => 17, 'name' => 'Jahun'],
            ['state_id' => 17, 'name' => 'Kafin Hausa'],
            ['state_id' => 17, 'name' => 'Kaugama'],
            ['state_id' => 17, 'name' => 'Kazaure'],
            ['state_id' => 17, 'name' => 'Kiri Kasamma'],
            ['state_id' => 17, 'name' => 'Maigatari'],
            ['state_id' => 17, 'name' => 'Malam Madori'],
            ['state_id' => 17, 'name' => 'Ringim'],
            ['state_id' => 17, 'name' => 'Roni'],
            ['state_id' => 17, 'name' => 'Sule Tankarkar'],
            ['state_id' => 17, 'name' => 'Taura'],
            ['state_id' => 17, 'name' => 'Yankwashi'],
            // Kaduna (23 LGAs)
            ['state_id' => 18, 'name' => 'Birnin Gwari'],
            ['state_id' => 18, 'name' => 'Chikun'],
            ['state_id' => 18, 'name' => 'Giwa'],
            ['state_id' => 18, 'name' => 'Igabi'],
            ['state_id' => 18, 'name' => 'Ikara'],
            ['state_id' => 18, 'name' => 'Jaba'],
            ['state_id' => 18, 'name' => "Jema'a"],
            ['state_id' => 18, 'name' => 'Kachia'],
            ['state_id' => 18, 'name' => 'Kaduna North'],
            ['state_id' => 18, 'name' => 'Kaduna South'],
            ['state_id' => 18, 'name' => 'Kagarko'],
            ['state_id' => 18, 'name' => 'Kajuru'],
            ['state_id' => 18, 'name' => 'Kaura'],
            ['state_id' => 18, 'name' => 'Kauru'],
            ['state_id' => 18, 'name' => 'Kubau'],
            ['state_id' => 18, 'name' => 'Kudan'],
            ['state_id' => 18, 'name' => 'Lere'],
            ['state_id' => 18, 'name' => 'Makarfi'],
            ['state_id' => 18, 'name' => 'Sabon Gari'],
            ['state_id' => 18, 'name' => 'Sanga'],
            ['state_id' => 18, 'name' => 'Soba'],
            ['state_id' => 18, 'name' => 'Zangon Kataf'],
            ['state_id' => 18, 'name' => 'Zaria'],
            // Kano (44 LGAs)
            ['state_id' => 19, 'name' => 'Ajingi'],
            ['state_id' => 19, 'name' => 'Albasu'],
            ['state_id' => 19, 'name' => 'Bagwai'],
            ['state_id' => 19, 'name' => 'Bebeji'],
            ['state_id' => 19, 'name' => 'Bichi'],
            ['state_id' => 19, 'name' => 'Bunkure'],
            ['state_id' => 19, 'name' => 'Dala'],
            ['state_id' => 19, 'name' => 'Dambatta'],
            ['state_id' => 19, 'name' => 'Dawakin Kudu'],
            ['state_id' => 19, 'name' => 'Dawakin Tofa'],
            ['state_id' => 19, 'name' => 'Doguwa'],
            ['state_id' => 19, 'name' => 'Fagge'],
            ['state_id' => 19, 'name' => 'Gabasawa'],
            ['state_id' => 19, 'name' => 'Garko'],
            ['state_id' => 19, 'name' => 'Garun Mallam'],
            ['state_id' => 19, 'name' => 'Gaya'],
            ['state_id' => 19, 'name' => 'Gezawa'],
            ['state_id' => 19, 'name' => 'Gwale'],
            ['state_id' => 19, 'name' => 'Gwarzo'],
            ['state_id' => 19, 'name' => 'Kabo'],
            ['state_id' => 19, 'name' => 'Kano Municipal'],
            ['state_id' => 19, 'name' => 'Karaye'],
            ['state_id' => 19, 'name' => 'Kibiya'],
            ['state_id' => 19, 'name' => 'Kiru'],
            ['state_id' => 19, 'name' => 'Kumbotso'],
            ['state_id' => 19, 'name' => 'Kunchi'],
            ['state_id' => 19, 'name' => 'Kura'],
            ['state_id' => 19, 'name' => 'Madobi'],
            ['state_id' => 19, 'name' => 'Makoda'],
            ['state_id' => 19, 'name' => 'Minjibir'],
            ['state_id' => 19, 'name' => 'Nasarawa'],
            ['state_id' => 19, 'name' => 'Rano'],
            ['state_id' => 19, 'name' => 'Rimin Gado'],
            ['state_id' => 19, 'name' => 'Rogo'],
            ['state_id' => 19, 'name' => 'Shanono'],
            ['state_id' => 19, 'name' => 'Sumaila'],
            ['state_id' => 19, 'name' => 'Takai'],
            ['state_id' => 19, 'name' => 'Tarauni'],
            ['state_id' => 19, 'name' => 'Tofa'],
            ['state_id' => 19, 'name' => 'Tsanyawa'],
            ['state_id' => 19, 'name' => 'Tudun Wada'],
            ['state_id' => 19, 'name' => 'Ungogo'],
            ['state_id' => 19, 'name' => 'Warawa'],
            ['state_id' => 19, 'name' => 'Wudil'],
            // Katsina (34 LGAs)
            ['state_id' => 20, 'name' => 'Bakori'],
            ['state_id' => 20, 'name' => 'Batagarawa'],
            ['state_id' => 20, 'name' => 'Batsari'],
            ['state_id' => 20, 'name' => 'Baure'],
            ['state_id' => 20, 'name' => 'Bindawa'],
            ['state_id' => 20, 'name' => 'Charanchi'],
            ['state_id' => 20, 'name' => 'Dan Musa'],
            ['state_id' => 20, 'name' => 'Dandume'],
            ['state_id' => 20, 'name' => 'Danja'],
            ['state_id' => 20, 'name' => 'Daura'],
            ['state_id' => 20, 'name' => ' Dutsi'],
            ['state_id' => 20, 'name' => 'Dutsinma'],
            ['state_id' => 20, 'name' => 'Faskari'],
            ['state_id' => 20, 'name' => 'Funtua'],
            ['state_id' => 20, 'name' => 'Ingawa'],
            ['state_id' => 20, 'name' => 'Jibia'],
            ['state_id' => 20, 'name' => 'Kafur'],
            ['state_id' => 20, 'name' => 'Kaita'],
            ['state_id' => 20, 'name' => 'Kankara'],
            ['state_id' => 20, 'name' => 'Kankia'],
            ['state_id' => 20, 'name' => 'Katsina'],
            ['state_id' => 20, 'name' => 'Kurfi'],
            ['state_id' => 20, 'name' => 'Kusada'],
            ['state_id' => 20, 'name' => "Mai'adua"],
            ['state_id' => 20, 'name' => 'Malumfashi'],
            ['state_id' => 20, 'name' => 'Mani'],
            ['state_id' => 20, 'name' => 'Mashi'],
            ['state_id' => 20, 'name' => 'Mataizu'],
            ['state_id' => 20, 'name' => 'Musawa'],
            ['state_id' => 20, 'name' => 'Rimi'],
            ['state_id' => 20, 'name' => 'Sabuwa'],
            ['state_id' => 20, 'name' => 'Safana'],
            ['state_id' => 20, 'name' => 'Sandamu'],
            ['state_id' => 20, 'name' => 'Zango'],
            // Kebbi (21 LGAs)
            ['state_id' => 21, 'name' => 'Aliero'],
            ['state_id' => 21, 'name' => 'Arewa Dandi'],
            ['state_id' => 21, 'name' => 'Argungu'],
            ['state_id' => 21, 'name' => 'Augie'],
            ['state_id' => 21, 'name' => 'Bagudo'],
            ['state_id' => 21, 'name' => 'Birnin Kebbi'],
            ['state_id' => 21, 'name' => 'Bunza'],
            ['state_id' => 21, 'name' => 'Dandi'],
            ['state_id' => 21, 'name' => 'Fakai'],
            ['state_id' => 21, 'name' => 'Gwandu'],
            ['state_id' => 21, 'name' => 'Jega'],
            ['state_id' => 21, 'name' => 'Kalgo'],
            ['state_id' => 21, 'name' => 'Koko/Besse'],
            ['state_id' => 21, 'name' => 'Maiyama'],
            ['state_id' => 21, 'name' => 'Ngaski'],
            ['state_id' => 21, 'name' => 'Sakaba'],
            ['state_id' => 21, 'name' => 'Shanga'],
            ['state_id' => 21, 'name' => 'Suru'],
            ['state_id' => 21, 'name' => 'Wasagu/Danko'],
            ['state_id' => 21, 'name' => 'Yauri'],
            ['state_id' => 21, 'name' => 'Zuru'],
            // Kogi (21 LGAs)
            ['state_id' => 22, 'name' => 'Adavi'],
            ['state_id' => 22, 'name' => 'Ajaokuta'],
            ['state_id' => 22, 'name' => 'Ankpa'],
            ['state_id' => 22, 'name' => 'Bassa'],
            ['state_id' => 22, 'name' => 'Dekina'],
            ['state_id' => 22, 'name' => 'Ibaji'],
            ['state_id' => 22, 'name' => 'Idah'],
            ['state_id' => 22, 'name' => 'Igalamela-Odolu'],
            ['state_id' => 22, 'name' => 'Ijumu'],
            ['state_id' => 22, 'name' => 'Kabba/Bunu'],
            ['state_id' => 22, 'name' => 'Kogi'],
            ['state_id' => 22, 'name' => 'Lokoja'],
            ['state_id' => 22, 'name' => 'Mopa-Muro'],
            ['state_id' => 22, 'name' => 'Ofu'],
            ['state_id' => 22, 'name' => 'Ogbadibo'],
            ['state_id' => 22, 'name' => 'Ogori/Magongo'],
            ['state_id' => 22, 'name' => 'Okehi'],
            ['state_id' => 22, 'name' => 'Okene'],
            ['state_id' => 22, 'name' => 'Olamaboro'],
            ['state_id' => 22, 'name' => 'Omala'],
            ['state_id' => 22, 'name' => 'Yagba East'],
            ['state_id' => 22, 'name' => 'Yagba West'],
            // Kwara (16 LGAs)
            ['state_id' => 23, 'name' => 'Asa'],
            ['state_id' => 23, 'name' => 'Baruten'],
            ['state_id' => 23, 'name' => 'Edu'],
            ['state_id' => 23, 'name' => 'Ekiti'],
            ['state_id' => 23, 'name' => 'Ifelodun'],
            ['state_id' => 23, 'name' => 'Ilorin East'],
            ['state_id' => 23, 'name' => 'Ilorin South'],
            ['state_id' => 23, 'name' => 'Ilorin West'],
            ['state_id' => 23, 'name' => 'Irepodun'],
            ['state_id' => 23, 'name' => 'Isin'],
            ['state_id' => 23, 'name' => 'Kaiama'],
            ['state_id' => 23, 'name' => 'Moro'],
            ['state_id' => 23, 'name' => 'Offa'],
            ['state_id' => 23, 'name' => 'Oke-Ero'],
            ['state_id' => 23, 'name' => 'Oyun'],
            ['state_id' => 23, 'name' => 'Pategi'],
            // Lagos (20 LGAs)
            ['state_id' => 24, 'name' => 'Agege'],
            ['state_id' => 24, 'name' => 'Alimosho'],
            ['state_id' => 24, 'name' => 'Amuwo Odofin'],
            ['state_id' => 24, 'name' => 'Apapa'],
            ['state_id' => 24, 'name' => 'Badagry'],
            ['state_id' => 24, 'name' => 'Eti-Osa'],
            ['state_id' => 24, 'name' => 'Ibeju-Lekki'],
            ['state_id' => 24, 'name' => 'Ifako-Ijaye'],
            ['state_id' => 24, 'name' => 'Ikeja'],
            ['state_id' => 24, 'name' => 'Ikorodu'],
            ['state_id' => 24, 'name' => 'Kosofe'],
            ['state_id' => 24, 'name' => 'Lagos Island'],
            ['state_id' => 24, 'name' => 'Lagos Mainland'],
            ['state_id' => 24, 'name' => 'Mushin'],
            ['state_id' => 24, 'name' => 'Ojo'],
            ['state_id' => 24, 'name' => 'Oshodi-Isolo'],
            ['state_id' => 24, 'name' => 'Shomolu'],
            ['state_id' => 24, 'name' => 'Surulere'],
            ['state_id' => 24, 'name' => 'Ajeromi-Ifelodun'],
            ['state_id' => 24, 'name' => 'Ikorodu'],
            // Nasarawa (13 LGAs)
            ['state_id' => 25, 'name' => 'Akwanga'],
            ['state_id' => 25, 'name' => 'Awe'],
            ['state_id' => 25, 'name' => 'Doma'],
            ['state_id' => 25, 'name' => 'Karu'],
            ['state_id' => 25, 'name' => 'Keana'],
            ['state_id' => 25, 'name' => 'Keffi'],
            ['state_id' => 25, 'name' => 'Kokona'],
            ['state_id' => 25, 'name' => 'Lafia'],
            ['state_id' => 25, 'name' => 'Nasarawa'],
            ['state_id' => 25, 'name' => 'Nasarawa Egon'],
            ['state_id' => 25, 'name' => 'Obi'],
            ['state_id' => 25, 'name' => 'Toto'],
            ['state_id' => 25, 'name' => 'Wamba'],
            // Niger (25 LGAs)
            ['state_id' => 26, 'name' => 'Agaie'],
            ['state_id' => 26, 'name' => 'Agwara'],
            ['state_id' => 26, 'name' => 'Bida'],
            ['state_id' => 26, 'name' => 'Borgu'],
            ['state_id' => 26, 'name' => 'Bosso'],
            ['state_id' => 26, 'name' => 'Chanchaga'],
            ['state_id' => 26, 'name' => 'Edati'],
            ['state_id' => 26, 'name' => 'Gbako'],
            ['state_id' => 26, 'name' => 'Gurara'],
            ['state_id' => 26, 'name' => 'Katcha'],
            ['state_id' => 26, 'name' => 'Kontagora'],
            ['state_id' => 26, 'name' => 'Lapai'],
            ['state_id' => 26, 'name' => 'Lavun'],
            ['state_id' => 26, 'name' => 'Magama'],
            ['state_id' => 26, 'name' => 'Mariga'],
            ['state_id' => 26, 'name' => 'Mokwa'],
            ['state_id' => 26, 'name' => 'Muya'],
            ['state_id' => 26, 'name' => 'Paikoro'],
            ['state_id' => 26, 'name' => 'Rafi'],
            ['state_id' => 26, 'name' => 'Rijau'],
            ['state_id' => 26, 'name' => 'Shiroro'],
            ['state_id' => 26, 'name' => 'Suleja'],
            ['state_id' => 26, 'name' => 'Tafa'],
            ['state_id' => 26, 'name' => 'Wushishi'],
            // Ogun (20 LGAs)
            ['state_id' => 27, 'name' => 'Abeokuta North'],
            ['state_id' => 27, 'name' => 'Abeokuta South'],
            ['state_id' => 27, 'name' => 'Ado-Odo/Ota'],
            ['state_id' => 27, 'name' => 'Ewekoro'],
            ['state_id' => 27, 'name' => 'Ifo'],
            ['state_id' => 27, 'name' => 'Ijebu East'],
            ['state_id' => 27, 'name' => 'Ijebu North'],
            ['state_id' => 27, 'name' => 'Ijebu North East'],
            ['state_id' => 27, 'name' => 'Ijebu Ode'],
            ['state_id' => 27, 'name' => 'Ikenne'],
            ['state_id' => 27, 'name' => 'Imeko Afon'],
            ['state_id' => 27, 'name' => 'Ipokia'],
            ['state_id' => 27, 'name' => 'Obafemi Owode'],
            ['state_id' => 27, 'name' => 'Odeda'],
            ['state_id' => 27, 'name' => 'Odogbolu'],
            ['state_id' => 27, 'name' => 'Ogun Waterside'],
            ['state_id' => 27, 'name' => 'Remo North'],
            ['state_id' => 27, 'name' => 'Remo South'],
            ['state_id' => 27, 'name' => 'Sagamu'],
            ['state_id' => 27, 'name' => 'Yewa North'],
            ['state_id' => 27, 'name' => 'Yewa South'],
            // Ondo (18 LGAs)
            ['state_id' => 28, 'name' => 'Akoko North East'],
            ['state_id' => 28, 'name' => 'Akoko North West'],
            ['state_id' => 28, 'name' => 'Akoko South East'],
            ['state_id' => 28, 'name' => 'Akoko South West'],
            ['state_id' => 28, 'name' => 'Akure North'],
            ['state_id' => 28, 'name' => 'Akure South'],
            ['state_id' => 28, 'name' => 'Ese Odo'],
            ['state_id' => 28, 'name' => 'Idanre'],
            ['state_id' => 28, 'name' => 'Ifedore'],
            ['state_id' => 28, 'name' => 'Ilaje'],
            ['state_id' => 28, 'name' => 'Ile Oluji/Okeigbo'],
            ['state_id' => 28, 'name' => 'Irele'],
            ['state_id' => 28, 'name' => 'Odigbo'],
            ['state_id' => 28, 'name' => 'Okitipupa'],
            ['state_id' => 28, 'name' => 'Ondo East'],
            ['state_id' => 28, 'name' => 'Ondo West'],
            ['state_id' => 28, 'name' => 'Ose'],
            ['state_id' => 28, 'name' => 'Owo'],
            // Osun (30 LGAs)
            ['state_id' => 29, 'name' => 'Atakunmosa East'],
            ['state_id' => 29, 'name' => 'Atakunmosa West'],
            ['state_id' => 29, 'name' => 'Aiyedaade'],
            ['state_id' => 29, 'name' => 'Aiyegunle'],
            ['state_id' => 29, 'name' => 'Boluwaduro'],
            ['state_id' => 29, 'name' => 'Boripe'],
            ['state_id' => 29, 'name' => 'Ede North'],
            ['state_id' => 29, 'name' => 'Ede South'],
            ['state_id' => 29, 'name' => 'Ejigbo'],
            ['state_id' => 29, 'name' => 'Ife Central'],
            ['state_id' => 29, 'name' => 'Ife East'],
            ['state_id' => 29, 'name' => 'Ife North'],
            ['state_id' => 29, 'name' => 'Ife South'],
            ['state_id' => 29, 'name' => 'Ifelodun'],
            ['state_id' => 29, 'name' => 'Ilesa East'],
            ['state_id' => 29, 'name' => 'Ilesa West'],
            ['state_id' => 29, 'name' => 'Irepodun'],
            ['state_id' => 29, 'name' => 'Isokan'],
            ['state_id' => 29, 'name' => 'Iwo'],
            ['state_id' => 29, 'name' => 'Obokun'],
            ['state_id' => 29, 'name' => 'Odo-Otin'],
            ['state_id' => 29, 'name' => 'Ola Oluwa'],
            ['state_id' => 29, 'name' => 'Olorunda'],
            ['state_id' => 29, 'name' => 'Oriade'],
            ['state_id' => 29, 'name' => 'Orolu'],
            ['state_id' => 29, 'name' => 'Osogbo'],
            // Oyo (33 LGAs)
            ['state_id' => 30, 'name' => 'Afijio'],
            ['state_id' => 30, 'name' => 'Akinyele'],
            ['state_id' => 30, 'name' => 'Atiba'],
            ['state_id' => 30, 'name' => 'Atisbo'],
            ['state_id' => 30, 'name' => 'Egbeda'],
            ['state_id' => 30, 'name' => 'Ibadan North'],
            ['state_id' => 30, 'name' => 'Ibadan North East'],
            ['state_id' => 30, 'name' => 'Ibadan North West'],
            ['state_id' => 30, 'name' => 'Ibadan South East'],
            ['state_id' => 30, 'name' => 'Ibadan South West'],
            ['state_id' => 30, 'name' => 'Ibarapa Central'],
            ['state_id' => 30, 'name' => 'Ibarapa East'],
            ['state_id' => 30, 'name' => 'Ibarapa North'],
            ['state_id' => 30, 'name' => 'Ido'],
            ['state_id' => 30, 'name' => 'Ifedayo'],
            ['state_id' => 30, 'name' => 'Ifelodun'],
            ['state_id' => 30, 'name' => 'Irepo'],
            ['state_id' => 30, 'name' => 'Iseyin'],
            ['state_id' => 30, 'name' => 'Itesiwaju'],
            ['state_id' => 30, 'name' => 'Iwajowa'],
            ['state_id' => 30, 'name' => 'Kajola'],
            ['state_id' => 30, 'name' => 'Lagelu'],
            ['state_id' => 30, 'name' => 'Ogbomoso North'],
            ['state_id' => 30, 'name' => 'Ogbomoso South'],
            ['state_id' => 30, 'name' => 'Ogo Oluwa'],
            ['state_id' => 30, 'name' => 'Olorunsogo'],
            ['state_id' => 30, 'name' => 'Oluyole'],
            ['state_id' => 30, 'name' => 'Ona Ara'],
            ['state_id' => 30, 'name' => 'Orelope'],
            ['state_id' => 30, 'name' => 'Ori Ire'],
            ['state_id' => 30, 'name' => 'Oyo'],
            ['state_id' => 30, 'name' => 'Oyo East'],
            ['state_id' => 30, 'name' => 'Saki East'],
            ['state_id' => 30, 'name' => 'Saki West'],
            ['state_id' => 30, 'name' => 'Surulere'],
            // Plateau (17 LGAs)
            ['state_id' => 31, 'name' => 'Barkin Ladi'],
            ['state_id' => 31, 'name' => 'Bassa'],
            ['state_id' => 31, 'name' => 'Bokkos'],
            ['state_id' => 31, 'name' => 'Jos East'],
            ['state_id' => 31, 'name' => 'Jos North'],
            ['state_id' => 31, 'name' => 'Jos South'],
            ['state_id' => 31, 'name' => 'Kanam'],
            ['state_id' => 31, 'name' => 'Kanke'],
            ['state_id' => 31, 'name' => 'Langtang North'],
            ['state_id' => 31, 'name' => 'Langtang South'],
            ['state_id' => 31, 'name' => 'Mangu'],
            ['state_id' => 31, 'name' => 'Mikang'],
            ['state_id' => 31, 'name' => 'Pankshin'],
            ['state_id' => 31, 'name' => "Qua'an Pan"],
            ['state_id' => 31, 'name' => 'Riyom'],
            ['state_id' => 31, 'name' => 'Shendam'],
            ['state_id' => 31, 'name' => 'Wase'],
            // Rivers (23 LGAs)
            ['state_id' => 32, 'name' => 'Abua/Odual'],
            ['state_id' => 32, 'name' => 'Ahoada East'],
            ['state_id' => 32, 'name' => 'Ahoada West'],
            ['state_id' => 32, 'name' => 'Akuku Toru'],
            ['state_id' => 32, 'name' => 'Andoni'],
            ['state_id' => 32, 'name' => 'Asari Toru'],
            ['state_id' => 32, 'name' => 'Bonny'],
            ['state_id' => 32, 'name' => 'Degema'],
            ['state_id' => 32, 'name' => 'Eleme'],
            ['state_id' => 32, 'name' => 'Emohua'],
            ['state_id' => 32, 'name' => 'Etche'],
            ['state_id' => 32, 'name' => 'Gokana'],
            ['state_id' => 32, 'name' => 'Ikwerre'],
            ['state_id' => 32, 'name' => 'Khana'],
            ['state_id' => 32, 'name' => 'Obio/Akpor'],
            ['state_id' => 32, 'name' => 'Ogba/Egbema/Ndoni'],
            ['state_id' => 32, 'name' => 'Oguta'],
            ['state_id' => 32, 'name' => 'Ohaji-Egbema'],
            ['state_id' => 32, 'name' => 'Okrika'],
            ['state_id' => 32, 'name' => 'Omuma'],
            ['state_id' => 32, 'name' => 'Opobo/Nkoro'],
            ['state_id' => 32, 'name' => 'Oyigbo'],
            ['state_id' => 32, 'name' => 'Port Harcourt'],
            ['state_id' => 32, 'name' => 'Tai'],
            // Sokoto (23 LGAs)
            ['state_id' => 33, 'name' => 'Binji'],
            ['state_id' => 33, 'name' => 'Bodinga'],
            ['state_id' => 33, 'name' => 'Dange Shuni'],
            ['state_id' => 33, 'name' => 'Gudu'],
            ['state_id' => 33, 'name' => 'Gwadabawa'],
            ['state_id' => 33, 'name' => 'Illela'],
            ['state_id' => 33, 'name' => 'Kebbe'],
            ['state_id' => 33, 'name' => 'Kware'],
            ['state_id' => 33, 'name' => 'Rabah'],
            ['state_id' => 33, 'name' => 'Sabon Birni'],
            ['state_id' => 33, 'name' => 'Shagari'],
            ['state_id' => 33, 'name' => 'Silame'],
            ['state_id' => 33, 'name' => 'Sokoto North'],
            ['state_id' => 33, 'name' => 'Sokoto South'],
            ['state_id' => 33, 'name' => 'Tambuwal'],
            ['state_id' => 33, 'name' => 'Tangaza'],
            ['state_id' => 33, 'name' => 'Tureta'],
            ['state_id' => 33, 'name' => 'Wamako'],
            ['state_id' => 33, 'name' => 'Wurno'],
            ['state_id' => 33, 'name' => 'Yabo'],
            // Taraba (16 LGAs)
            ['state_id' => 34, 'name' => 'Ardo Kola'],
            ['state_id' => 34, 'name' => 'Bali'],
            ['state_id' => 34, 'name' => 'Donga'],
            ['state_id' => 34, 'name' => 'Gashaka'],
            ['state_id' => 34, 'name' => 'Gassol'],
            ['state_id' => 34, 'name' => 'Ibi'],
            ['state_id' => 34, 'name' => 'Jalingo'],
            ['state_id' => 34, 'name' => 'Kurmi'],
            ['state_id' => 34, 'name' => 'Lau'],
            ['state_id' => 34, 'name' => 'Sardauna'],
            ['state_id' => 34, 'name' => 'Takum'],
            ['state_id' => 34, 'name' => 'Ussa'],
            ['state_id' => 34, 'name' => 'Wukari'],
            ['state_id' => 34, 'name' => 'Yorro'],
            ['state_id' => 34, 'name' => 'Zing'],
            // Yobe (17 LGAs)
            ['state_id' => 35, 'name' => 'Bade'],
            ['state_id' => 35, 'name' => 'Bursari'],
            ['state_id' => 35, 'name' => 'Damaturu'],
            ['state_id' => 35, 'name' => 'Fika'],
            ['state_id' => 35, 'name' => 'Fune'],
            ['state_id' => 35, 'name' => 'Geidam'],
            ['state_id' => 35, 'name' => 'Gujba'],
            ['state_id' => 35, 'name' => 'Gulani'],
            ['state_id' => 35, 'name' => 'Jakusko'],
            ['state_id' => 35, 'name' => 'Karasuwa'],
            ['state_id' => 35, 'name' => 'Machina'],
            ['state_id' => 35, 'name' => 'Nangere'],
            ['state_id' => 35, 'name' => 'Nguru'],
            ['state_id' => 35, 'name' => 'Potiskum'],
            ['state_id' => 35, 'name' => 'Tarmuwa'],
            ['state_id' => 35, 'name' => 'Yunusari'],
            ['state_id' => 35, 'name' => 'Yusufari'],
            // Zamfara (14 LGAs)
            ['state_id' => 36, 'name' => 'Anka'],
            ['state_id' => 36, 'name' => 'Birnin Magaji'],
            ['state_id' => 36, 'name' => 'Bukkuyum'],
            ['state_id' => 36, 'name' => 'Bungudu'],
            ['state_id' => 36, 'name' => 'Chafe'],
            ['state_id' => 36, 'name' => 'Gummi'],
            ['state_id' => 36, 'name' => 'Gusau'],
            ['state_id' => 36, 'name' => 'Kaura Namoda'],
            ['state_id' => 36, 'name' => 'Maradun'],
            ['state_id' => 36, 'name' => 'Maru'],
            ['state_id' => 36, 'name' => 'Shinkafi'],
            ['state_id' => 36, 'name' => 'Talata Mafara'],
            ['state_id' => 36, 'name' => 'Zurmi'],
            // Federal Capital Territory (6 LGAs)
            ['state_id' => 37, 'name' => 'Abaji'],
            ['state_id' => 37, 'name' => 'Bwari'],
            ['state_id' => 37, 'name' => 'Gwagwalada'],
            ['state_id' => 37, 'name' => 'Kuje'],
            ['state_id' => 37, 'name' => 'Kwali'],
            ['state_id' => 37, 'name' => 'Municipal Area Council'],
        ];

        foreach ($lgas as $lga) {
            LocalGovernment::firstOrCreate(
                ['name' => $lga['name'], 'state_id' => $lga['state_id']],
                $lga
            );
        }
    }
}
