services:
  - type: web
    name: portal
    env: php
    buildCommand: |
      php -r "file_exists('.env') || copy('.env.example', '.env');"
      composer install --optimize-autoloader --no-dev
    startCommand: php artisan serve --host=0.0.0.0 --port=10000