<?php

namespace Tests\Feature\Applicant;

use App\Models\Applicant;
use App\Models\Department;
use App\Models\PaymentType;
use App\Models\Programme;
use App\Models\Role;
use App\Models\School;
use App\Models\Session as AcademicSession;
use App\Models\Student;
use App\Models\User;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

/**
 * Pins the dashboard "Admission Details" Level cell rendering.
 *
 * Bug: the view used to read `$applicant->level`, but the `applicants`
 * table has no `level` column — so the literal text `00 Level` was
 * rendered (null concatenated with the literal "00 Level"). The view
 * now reads `$applicant->student->level` (canonical int 1..7) and
 * multiplies by 100, so a 100L admit renders as `100 Level`.
 *
 * Pinned behaviour:
 *   - migrated applicant (student.level = 1) → dashboard shows `100 Level`
 *   - migrated applicant (student.level = 2) → dashboard shows `200 Level`
 *   - dashboard NEVER shows `00 Level` (the buggy literal)
 */
class ApplicantDashboardLevelTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();
        $this->buildSchema();
        $this->seedFixtures();
    }

    protected function tearDown(): void
    {
        Schema::dropIfExists('external_payments');
        Schema::dropIfExists('system_settings');
        Schema::dropIfExists('payments');
        Schema::dropIfExists('payment_types');
        Schema::dropIfExists('students');
        Schema::dropIfExists('applicants');
        Schema::dropIfExists('users');
        Schema::dropIfExists('programmes');
        Schema::dropIfExists('departments');
        Schema::dropIfExists('schools');
        Schema::dropIfExists('sessions');
        Schema::dropIfExists('roles');
        parent::tearDown();
    }

    public function test_dashboard_renders_100_level_for_fresh_admit(): void
    {
        $applicant = $this->makeMigratedApplicant(level: 1);

        $response = $this->actingAs($applicant->user)->get('/applicant/dashboard');

        $response->assertOk();
        $response->assertSee('100 Level', false);
        // Defend against the literal "00 Level" appearing as the entire
        // cell content (the original bug).
        $response->assertDontSee('>00 Level<', false);
    }

    public function test_dashboard_renders_200_level_for_200l_admit(): void
    {
        $applicant = $this->makeMigratedApplicant(level: 2);

        $response = $this->actingAs($applicant->user)->get('/applicant/dashboard');

        $response->assertOk();
        $response->assertSee('200 Level', false);
        // Note: "200 Level" contains "00 Level" as a substring, so we
        // anchor on the surrounding TD tag rather than doing a raw
        // substring check.
        $response->assertDontSee('>00 Level<', false);
    }

    public function test_dashboard_renders_500_level_for_500l_admit(): void
    {
        $applicant = $this->makeMigratedApplicant(level: 5);

        $response = $this->actingAs($applicant->user)->get('/applicant/dashboard');

        $response->assertOk();
        $response->assertSee('500 Level', false);
    }

    public function test_dashboard_falls_back_to_entry_level_pre_migration(): void
    {
        // Pre-migration: applicant has no student row. View should fall
        // back to applicants.entry_level. We pre-set a matric_number on
        // the applicant so the Admission Details card (gated on
        // matric_number being set) renders and we can read the Level
        // cell. The matric is generated by the canonical
        // MatricNumberService when the registrar clicks "Admit", so
        // this state is realistic.
        $applicant = $this->makeAdmittedApplicant(entryLevel: '1');
        $applicant->update([
            'matric_number' => 'EKSCOTECH/COM/' . substr((string) date('Y'), -2) . '/001',
        ]);

        $response = $this->actingAs($applicant->user)->get('/applicant/dashboard');

        $response->assertOk();
        $response->assertSee('100 Level', false);
        $response->assertDontSee('>00 Level<', false);
    }

    /* --- helpers --- */

    private function makeMigratedApplicant(int $level): Applicant
    {
        $applicant = $this->makeAdmittedApplicant();

        $student = Student::create([
            'user_id'       => $applicant->user_id,
            'matric_number' => 'EKSCOTECH/COM/' . substr((string) date('Y'), -2) . '/001',
            'school_id'     => $applicant->school_id,
            'department_id' => $applicant->department_id,
            'programme_id'  => $applicant->programme_id,
            'session_id'    => $applicant->session_id,
            'level'         => $level,
            'status'        => 'active',
        ]);

        $studentRole = Role::where('slug', 'student')->first();
        if ($studentRole) {
            User::where('id', $applicant->user_id)->update(['role_id' => $studentRole->id]);
        }

        $applicant->update([
            'student_id'           => $student->id,
            'matric_number'        => $student->matric_number,
            'migrated_to_student_at' => now(),
        ]);

        return $applicant->refresh();
    }

    private function makeAdmittedApplicant(?string $entryLevel = null): Applicant
    {
        $user = User::create([
            'name'  => 'Admitted Applicant',
            'email' => 'admitted_' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'role_id'  => Role::where('slug', 'applicant')->value('id'),
            'is_active' => true,
        ]);

        return Applicant::create([
            'user_id'            => $user->id,
            'email'              => $user->email,
            'application_number' => Applicant::generateApplicationNumber(),
            'status'             => 'admitted',
            'school_id'          => School::first()->id,
            'department_id'      => Department::first()->id,
            'programme_id'       => Programme::first()->id,
            'session_id'         => AcademicSession::first()->id,
            'entry_level'        => $entryLevel,
        ]);
    }

    private function buildSchema(): void
    {
        Schema::create('roles', function ($t) {
            $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->timestamps();
        });
        Schema::create('schools', function ($t) {
            $t->id(); $t->string('name'); $t->string('code')->unique(); $t->timestamps();
        });
        Schema::create('departments', function ($t) {
            $t->id();
            $t->string('name');
            $t->string('code')->unique();
            $t->foreignId('school_id')->constrained();
            $t->timestamps();
        });
        Schema::create('programmes', function ($t) {
            $t->id();
            $t->string('name');
            $t->string('code')->unique();
            $t->foreignId('department_id')->constrained();
            $t->timestamps();
        });
        Schema::create('sessions', function ($t) {
            $t->id(); $t->string('name'); $t->boolean('is_current')->default(false); $t->timestamps();
        });
        Schema::create('users', function ($t) {
            $t->id();
            $t->string('name');
            $t->string('email')->unique();
            $t->string('password');
            $t->foreignId('role_id')->nullable()->constrained();
            $t->boolean('is_active')->default(true);
            $t->timestamps();
        });
        Schema::create('applicants', function ($t) {
            $t->id();
            $t->foreignId('user_id')->nullable()->constrained();
            $t->string('application_number')->unique();
            $t->string('first_name')->nullable();
            $t->string('surname')->nullable();
            $t->string('middle_name')->nullable();
            $t->string('email')->nullable();
            $t->string('phone')->nullable();
            $t->string('status', 20)->default('pending');
            $t->foreignId('school_id')->nullable()->constrained();
            $t->foreignId('department_id')->nullable()->constrained();
            $t->foreignId('programme_id')->nullable()->constrained();
            $t->foreignId('session_id')->nullable()->constrained();
            $t->string('mode_of_study')->nullable();
            $t->string('entry_level')->nullable();
            $t->string('payment_status', 20)->default('pending');
            $t->dateTime('application_paid_at')->nullable();
            $t->dateTime('acceptance_paid_at')->nullable();
            $t->dateTime('compulsory_paid_at')->nullable();
            $t->dateTime('migrated_to_student_at')->nullable();
            $t->foreignId('student_id')->nullable();
            $t->string('matric_number')->nullable();
            $t->integer('level')->nullable();
            $t->timestamps();
        });
        Schema::create('students', function ($t) {
            $t->id();
            $t->foreignId('user_id')->nullable()->constrained();
            $t->string('matric_number')->nullable();
            $t->foreignId('school_id')->nullable()->constrained();
            $t->foreignId('department_id')->nullable()->constrained();
            $t->foreignId('programme_id')->nullable()->constrained();
            $t->foreignId('session_id')->nullable()->constrained();
            $t->integer('level')->nullable();
            $t->string('status', 20)->default('active');
            $t->timestamps();
        });
        Schema::create('payment_types', function ($t) {
            $t->id();
            $t->string('name');
            $t->string('code')->unique();
            $t->string('purpose')->nullable();
            $t->decimal('amount', 12, 2)->default(0);
            $t->boolean('is_active')->default(true);
            $t->boolean('requires_payment')->default(true);
            $t->string('payment_channel')->nullable();
            $t->integer('priority')->default(0);
            $t->enum('audience', ['applicant', 'student', 'both'])->default('both');
            $t->timestamps();
        });
        Schema::create('payments', function ($t) {
            $t->id();
            $t->foreignId('student_id')->nullable();
            $t->foreignId('fee_id')->nullable();
            $t->decimal('amount', 12, 2);
            $t->decimal('total_amount', 12, 2)->nullable();
            $t->string('reference')->nullable();
            $t->string('payment_ref')->nullable();
            $t->string('transaction_id')->nullable();
            $t->string('gateway')->nullable();
            $t->string('payment_method')->nullable();
            $t->string('status', 20)->default('pending');
            $t->boolean('is_verified')->default(false);
            $t->string('student_type')->nullable();
            $t->string('payment_purpose')->nullable();
            $t->string('fee_type')->nullable();
            $t->foreignId('payer_id')->nullable();
            $t->dateTime('payment_date')->nullable();
            $t->timestamps();
        });
        Schema::create('system_settings', function ($t) {
            $t->id();
            $t->string('key')->unique();
            $t->text('value')->nullable();
            $t->boolean('is_active')->default(true);
            $t->timestamps();
        });
        Schema::create('external_payments', function ($t) {
            $t->id();
            $t->foreignId('applicant_id')->nullable();
            $t->string('reference')->nullable();
            $t->string('status', 20)->default('pending');
            $t->decimal('amount', 12, 2)->default(0);
            $t->string('gateway')->nullable();
            $t->string('transaction_id')->nullable();
            $t->dateTime('payment_date')->nullable();
            $t->dateTime('paid_at')->nullable();
            $t->string('payment_status', 20)->default('pending');
            $t->timestamps();
        });
    }

    private function seedFixtures(): void
    {
        Role::create(['name' => 'Applicant', 'slug' => 'applicant']);
        Role::create(['name' => 'Student',   'slug' => 'student']);
        $school = School::create(['name' => 'Test School', 'code' => 'TST']);
        $dept = Department::create([
            'name' => 'Computer Studies',
            'code' => 'COM',
            'school_id' => $school->id,
        ]);
        Programme::create(['name' => 'Computer Science', 'code' => 'CSC', 'department_id' => $dept->id]);
        AcademicSession::create(['name' => '2025/2026', 'is_current' => true]);

        // Seed the payment_types the dashboard view reads.
        PaymentType::create([
            'name' => 'Application Form Fee', 'code' => 'APP_FORM',
            'purpose' => PaymentType::PURPOSE_APPLICATION,
            'amount' => 5000, 'audience' => PaymentType::AUDIENCE_APPLICANT,
            'is_active' => true, 'requires_payment' => true, 'priority' => 1,
        ]);
        PaymentType::create([
            'name' => 'Acceptance Fee', 'code' => 'ACCEPT_FEE',
            'purpose' => PaymentType::PURPOSE_ACCEPTANCE,
            'amount' => 25000, 'audience' => PaymentType::AUDIENCE_APPLICANT,
            'is_active' => true, 'requires_payment' => true, 'priority' => 2,
        ]);
        PaymentType::create([
            'name' => 'Compulsory Fee', 'code' => 'COMP_FEE',
            'purpose' => PaymentType::PURPOSE_COMPULSORY,
            'amount' => 30000, 'audience' => PaymentType::AUDIENCE_APPLICANT,
            'is_active' => true, 'requires_payment' => true, 'priority' => 3,
        ]);
    }
}